---
title: "Kulturlabor"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = F)



################################################################################
## Initialize Environment ######################################################
################################################################################

library(tidyverse)
library(sf)
library(plotly)
library(raster)
library(gstat)

library(gganimate)


df2sf <- function(df,width,height){
  
  x_vec = c(0,1,1,0,0)*width
  y_vec = c(0,0,1,1,0)*height
  
  
 df %>%
  mutate(
    geometry =  map2(x,y,function(x_val,y_val){
      cbind(
        map2_dbl(x_vec,y_vec,~(.x+x_val)),
        map2_dbl(x_vec,y_vec,~(.y+y_val))
      )
    }
    )
  ) %>% 
  mutate(
    geometry = map(geometry,~st_polygon(list(.x))),
    geometry = st_sfc(geometry)
  ) %>%
  st_sf()
}


################################################################################
## Setup Study Design (create shapes) ##########################################
################################################################################


width = 2
height = 1.80
edge_width = 0.55
edge_height = 0.45

square_inner = height - edge_height*2

tische_df <- tibble(
  y = height*0:3,
  x = rep(0,4),
  tischnr = 1:4
)

tische_sf <- df2sf(tische_df,width,height)


logger_df <- tische_df %>%
  mutate(
    x = x + edge_width,
    y = y + edge_height
  )

logger_spacing = 0.45

logger_df %>%
  mutate(
    data = map2(x,y,function(x,y){
      x_org <- x
      y_org <- y
      x <- x_org+c(0,2)*logger_spacing
      y <- y_org+c(0,2)*logger_spacing
      crossing(x,y) %>%
        rbind(
          data_frame(
            x = x_org+1*logger_spacing,
            y = y_org+1*logger_spacing)
        ) %>%
        mutate(
          sensor = letters[1:nrow(.)]
        )
    })
  ) %>%
  dplyr::select(-c(x,y)) %>%
  unnest() %>%
  mutate(
    geometry = map2(x,y,~st_point(c(.x,.y))),
    geometry = st_sfc(geometry)
  ) -> logger_sf




################################################################################
## Create some dummy data ######################################################
################################################################################




werte <- crossing(
  hour = 1:24,
  tischnr = 1:4,
  sensor = letters[1:5]
) %>%
  mutate(
    factor_hour = hour*0.2/23+0.95,
  )

loggerwerte <- left_join(logger_sf,werte,by = c("tischnr","sensor")) %>%
  st_sf()

loggerwerte <- loggerwerte %>%
  mutate(
    factor_x = x*0.3/(max(x)-min(x))+0.8,
    factor_y = y*0.3/(max(y)-min(y))+0.8,
    tempmean = factor_x*factor_y*15,
    temperatur = map_dbl(tempmean,~rnorm(n = 1,mean = .x,sd = 2))
  )


loggerwerte %>%
  ggplot(aes(y,temperatur)) + geom_point()



coordinates_add <- function(input){
  cbind(input,sp::coordinates(input))
}


idw2raster <- function(loggerwerte,tische_sf, resolution = 0.1){
  points2interpolate_sp <- st_make_grid(tische_sf,square = T,cellsize = resolution/2,what = "centers") %>%
    as_Spatial(T)
  
  
  loggerwerte_sp <- sf::as_Spatial(loggerwerte,T)
  raster_template <- raster(extent(coordinates(points2interpolate_sp)), resolution = resolution)
  
  
  interpolated <- loggerwerte_sp %>%
    split(.$hour) %>%
    map(function(x){
      interpol <- idw(formula=temperatur ~ 1, locations = x, newdata = points2interpolate_sp, idp = 2.0)
    })
}

loggerwerte_hour <- loggerwerte %>%
  mutate(temp_short = format(round(temperatur), nsmall = 2)) %>%
  split(.$hour)



interpolated <- idw2raster(loggerwerte,tische_sf,0.05)

interpolated_df <- imap_dfr(interpolated, ~as.data.frame(.x) %>% mutate(hour = .y))



minval <- min(interpolated_df$var1.pred)
maxval <- max(interpolated_df$var1.pred)
  

 
  

```



```{r}

library(ggisoband)
anim <- interpolated_df %>%
  mutate(hour = as.integer(hour)) %>%
  # filter(hour < 2) %>%
  ggplot(aes(coords.x1,coords.x2)) +
  geom_raster(aes(fill = var1.pred)) +
  geom_isobands(binwidth = 5, aes(z = var1.pred), fill = NA,  polygon_outline = T)  +
  geom_sf(data = tische_sf, fill = NA,inherit.aes = F) +
  scale_fill_viridis_c(name = "Temperatur", limits = c(minval,maxval)) +
  geom_point(data = as.data.frame(loggerwerte), aes(x,y),fill = NA,shape = 1,inherit.aes = F) +
  geom_text(data = loggerwerte, aes(x,y,label = format(round(temperatur,1),nsmall = 1)),nudge_x = 0.15,nudge_y = 0.15,size = 2,) +
  # labs(title="Uhrzeit: {closest_state}")+
  labs(title="Uhrzeit: {frame_time}")+
  theme(
    axis.title = element_blank(),
    panel.grid.minor = element_line(linetype = 3,colour = "grey"),
    panel.grid.major = element_line(linetype = 2,colour = "black"),
    panel.background = element_rect(fill = "white"),
  ) +
  transition_time(hour)


animate(anim, fps = 10, duration = 20)
```


